"""Generate the experiment's DCN401 register subset from a Linux v6.16 source tree."""
import argparse, re
from pathlib import Path

PATTERN = re.compile(r"DMCUB_.*|DCN_VM_.*|MMHUBBUB_SOFT_RESET|CC_DC_PIPE_DIS|HPD[0-3]_DC_HPD_.*|"
  r"OTG[0-3]_.*|ODM0_.*|OPP_PIPE0_.*|VTG0_.*|DPG0_.*|FMT0_.*|DIG[0-3]_.*|OTG_PIXEL_RATE_DIV|"
  r"DENTIST_DISPCLK_CNTL|DC_GPIO_DDC[1-4]_.*|DC_I2C_.*|DIO_AUX[0-3]_AUX_CONTROL|"
  r"PHY_MUX[0-3]_.*|SYMCLK[A-D]_CLOCK_ENABLE|PHY[A-D]SYMCLK_CLOCK_CNTL|DIO_LINK[A-D]_CNTL|PHYPLL[A-D]_PIXCLK_RESYNC_CNTL|"
  r"HUBP0_.*|HUBPREQ0_.*|HUBPRET0_.*|DPP_TOP0_.*|CNVC_CFG0_.*|DSCL0_.*|"
  r"MPCC0_.*|MPC_.*|CM0_.*|COMPBUF_RESERVED_SPACE|DCHUBBUB_.*|DPPCLK.*|DOMAIN[0-9]+_.*|DC_IP_REQUEST_CNTL|DCCG_GATE_DISABLE_CNTL[0-9]+")

def generate(source:Path) -> str:
  base = source / "drivers/gpu/drm/amd/include/asic_reg/dcn"
  offsets = {k: int(v, 0) for k, v in re.findall(r"^#define reg(\w+)\s+(0x[\da-fA-F]+|\d+)\s*$",
    (base / "dcn_4_1_0_offset.h").read_text(), re.M)}
  fields:dict[str, dict[str, tuple[int, int]]] = {}
  for reg, field, value in re.findall(r"^#define (\w+?)__(\w+)_MASK\s+(0x[\da-fA-F]+)L?\s*$",
                                    (base / "dcn_4_1_0_sh_mask.h").read_text(), re.M):
    if not PATTERN.fullmatch(reg): continue
    mask = int(value, 16)
    if mask == 0: raise ValueError(f"Empty mask: {reg}.{field}")
    low, high = (mask & -mask).bit_length() - 1, mask.bit_length() - 1
    if mask != ((1 << (high - low + 1)) - 1) << low: raise ValueError(f"Noncontiguous mask: {reg}.{field}")
    fields.setdefault(reg, {})[field.lower()] = (low, high)
  lines = ["# Generated by autogen/generate.py from Linux v6.16 DCN 4.1.0 headers.", "REGS = {"]
  for name, offset in offsets.items():
    if name.endswith("_BASE_IDX") or not PATTERN.fullmatch(name): continue
    lines.append(f"  {name!r}: ({offset:#x}, {offsets[name + '_BASE_IDX']}, {fields.get(name, {})!r}),")
  return "\n".join(lines + ["}", ""])

if __name__ == "__main__":
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument("linux", type=Path)
  args = parser.parse_args()
  Path(__file__).with_name("dcn_4_1_0.py").write_text(generate(args.linux))
